```{r}
df=train
```

```{r}
str(df)
dim(df)
```

```{r}
sum(is.na(df))
```


```{r}
library(DataExplorer)
plot_intro(df)
```
```{r}
plot_scatterplot(df,by="price_range")
```

```{r}
plot_density(df)
```

```{r}
plot_histogram(df)
```

```{r}
boxplot(df)
```

```{r}
plot_bar(df)
```
```{r}
class(df$price_range)="character"
plot_bar(df,by="price_range")
```


```{r}
library(corrplot)
my_corr=cor(df)
corrplot(my_corr)
```

```{r}
plot_correlation(df)
```

```{r}
#install.packages("yarrr")
library(yarrr)
```

```{r}
#install.packages("esquisse")
library(esquisse)
library(ggplot2)
```

```{r}
#esquisser(df)
```

```{r}
ggplot(df) +
  aes(x = battery_power) +
  geom_density(adjust = 1L, fill = "#EF2D2D") +
  theme_minimal()
```

```{r}
library(caTools)
set.seed(100)
split=sample.split(df,SplitRatio = 0.8)
Train=subset(df,split=="TRUE")
Test=subset(df,split=="FALSE")
```

```{r}
#library(randomForest)
model <- randomForest(as.factor(price_range)~.,data = Train, maxdepth = 2)
model
```


```{r}
plot(model)
```


```{r}
library(dplyr)
out.importance <- round(importance(model), 2)
out.importance

```
```{r}
y_pred=predict(model,Test)
head(y_pred,10)
```


```{r}
library(Metrics)
accuracy(Test$price_range,y_pred)
```

```{r}
recall(Test$price_range,y_pred)
```


```{r}
precision(Test$price_range,y_pred)
```



